---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - cilium-networkpolicy.yaml
# Base resources managed by Helm
components:
  - ../../../_shared/components/revision-history-limit
