---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: adguard-home
spec:
  endpointSelector:
    matchLabels:
      app: adguard-home
  ingress:
    - fromEntities:
        - host
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "3000"
              protocol: TCP
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
