---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    app: adguard-home
    vixens.io/sizing: G-small
    vixens.io/backup-profile: "relaxed"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
        vixens.io/sizing.adguard-home: G-small
        vixens.io/backup-profile: "relaxed"
      annotations:
        vixens.io/fast-start: "true"
        reloader.stakater.com/auto: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        goldilocks.fairwinds.com/enabled: "true"
        autoscaling.k8s.io/vpa: auto
        vixens.io/no-long-connections: "true"
    spec:
      priorityClassName: vixens-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      initContainers: []
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.74
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_BIND_SERVICE"]
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: config
              mountPath: /opt/adguardhome/conf
            - name: data
              mountPath: /opt/adguardhome/work
      volumes:
        - name: config
          emptyDir: {}
        - name: data
          emptyDir: {}
