---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi-xfs-retain
  resources:
    requests:
      storage: 5Gi
