---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi-xfs-retain
  resources:
    requests:
      storage: 5Gi
