---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: nexterm-secrets-sync
  namespace: tools
spec:
  authentication:
    universalAuth:
      secretsScope:
        envSlug: prod
