---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../_shared/components/dev-hibernate

patches:
  - target:
      kind: Ingress
      name: trilium
    patch: |-
      - op: replace
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt-staging
      - op: replace
        path: /spec/rules/0/host
        value: trilium.dev.truxonline.com
      - op: replace
        path: /spec/tls/0/hosts/0
        value: trilium.dev.truxonline.com
      - op: replace
        path: /spec/tls/0/secretName
        value: trilium-tls-dev
