---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  labels:
    k8s-app: kube-dns
    app.kubernetes.io/name: coredns
    app.kubernetes.io/managed-by: argocd
data:
  Corefile: |
    internal.truxonline.com:53 {
        errors
        cache 30
        forward . 192.168.200.21 192.168.200.22 {
            policy sequential
            max_concurrent 1000
        }
    }

    truxonline.com:53 {
        errors
        cache 30
        forward . 192.168.201.1 {
            max_concurrent 1000
        }
    }

    .:53 {
        errors
        health {
            lameduck 5s
        }
        ready
        log . {
            class error
        }
        prometheus :9153
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        forward . adguard-home.networking.svc.cluster.local {
            resolver 10.96.0.10
            max_concurrent 1000
        }
        cache 30 {
            disable success cluster.local
            disable denial cluster.local
        }
        loop
        reload
        loadbalance
    }
