---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sogo
  namespace: sogo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Services
    gethomepage.dev/name: SOGo
    gethomepage.dev/icon: sogo.svg
    gethomepage.dev/description: Webmail + Calendar + Contacts
spec:
  ingressClassName: traefik
  rules:
    - host: sogo.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sogo
                port:
                  number: 80
  tls:
    - hosts:
        - sogo.truxonline.com
      secretName: sogo-tls
