---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: synelia-snapshot-retain
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: csi.san.synology.com
deletionPolicy: Retain
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: synelia-snapshot-delete
driver: csi.san.synology.com
deletionPolicy: Delete
