---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shelfarr-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Shelfarr
    gethomepage.dev/group: Test
spec:
  ingressClassName: traefik
  rules:
    - host: shelfarr.dev.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shelfarr
                port:
                  number: 80
  tls:
    - hosts:
        - shelfarr.dev.truxonline.com
      secretName: shelfarr-tls-dev
