---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hairem-files-truenas
  namespace: services
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-retain
  resources:
    requests:
      storage: 20Gi
