---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    environment: dev
resources:
- ../../base
- infisical-secret.yaml
- ingress.yaml
components:
- ../../../../_shared/components/dev-hibernate
