---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
  labels:
    app: music-assistant
    vixens.io/vpa-mode: Auto
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
        vixens.io/sizing.music-assistant: V-medium
        vixens.io/backup-profile: "relaxed"
      annotations:
        vixens.io/no-long-connections: "true"
        vixens.io/explicitly-allow-root: "true"
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      priorityClassName: vixens-medium
      containers:
        - name: music-assistant
          resources:
            requests:
              cpu: 50m
              memory: 512Mi
            limits:
              cpu: 200m
              memory: 2Gi
          image: ghcr.io/music-assistant/server:2.8.0rc1
          ports:
            - containerPort: 8095
              name: web
            - containerPort: 3483
              name: slimproto-tcp
              protocol: TCP
            - containerPort: 3483
              name: slimproto-udp
              protocol: UDP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Paris
          volumeMounts:
            - name: config
              mountPath: /data
            - name: media
              mountPath: /media
          livenessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 20
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: music-assistant-config-pvc
        - name: media
          nfs:
            server: 192.168.111.69
            path: /volume3/Content/music
