---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdnet-go
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.birdnet-go: G-medium
        vixens.io/sizing.litestream: G-small
        vixens.io/sizing.data-syncer: G-small
    spec:
