---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    vixens.io/sizing.radarr: medium
    vixens.io/sizing.litestream: small
    vixens.io/sizing.config-syncer: small
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.radarr: medium
        vixens.io/sizing.litestream: small
        vixens.io/sizing.config-syncer: small
