---
lapi:
  env:
    - name: BOUNCER_KEY_traefik
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: CROWDSEC_BOUNCER_KEY
    - name: ENROLL_INSTANCE_NAME
      value: "vixens-k8s-prod"
    - name: ENROLL_TAGS
      value: "k8s linux homelab prod"
    - name: CROWDSEC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-secrets
          key: CROWDSEC_DB_PASSWORD
