---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-home-secrets-sync
  namespace: networking
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/40-network/adguard-home
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
