---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace-system.yaml
  - namespace-tenant-indiba.yaml
  - crd-hermesruntime.yaml
  - serviceaccounts.yaml
  - rbac.yaml
  - services.yaml
  - configmap-contracts.yaml
  - portal-app.yaml
  - networkpolicy-system.yaml
  - portal-networkpolicy.yaml
  - cilium-system-egress.yaml
  - networkpolicy-tenant-indiba.yaml
