apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: external-dns-gandi
  namespace: networking
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: external-dns-gandi
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
