---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-gandi-sync
  namespace: networking
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: external-dns-gandi-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/dev/apps/40-network/external-dns/gandi
