---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trilium-secrets-sync
  namespace: tools
  labels:
    app.kubernetes.io/name: trilium
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: trilium-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/prod/apps/70-tools/trilium
