---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    vixens.io/sizing: medium
spec:
  template:
    metadata:
      labels:
        app: prowlarr
        vixens.io/sizing: medium
