---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-snmp.yaml
  - configmap-vmscrape-tpl.yaml
  - deployment.yaml
  - service.yaml
  - infisical-secret.yaml
  - rbac.yaml
  - vmscrape.yaml
