---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ../../base
  - ingress.yaml
components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-10
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/dataangel
  - ../../../../_shared/components/poddisruptionbudget/1

patches:
  - path: dataangel.yaml
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path-retain
    target:
      kind: PersistentVolumeClaim
      name: sabnzbd-config-pvc
