---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: penpot-backend
spec:
  endpointSelector:
    matchLabels:
      app: penpot-backend
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "6060"
              protocol: TCP
