---
apiVersion: v1
kind: ConfigMap
metadata:
  name: whisparr-litestream-config
data:
  litestream.yml: |
    dbs:
      - path: /config/whisparr2.db
        replicas:
          - url: s3://$LITESTREAM_BUCKET/whisparr2.db
            endpoint: $LITESTREAM_ENDPOINT
    addr: ":9090"
