---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keda-admission-webhooks
  namespace: keda
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keda-admission-webhooks
