apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii-importer
  labels:
    app.kubernetes.io/name: firefly-iii-importer
    vixens.io/sizing-v2: "true"
    vixens.io/vpa-mode: Auto
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: firefly-iii-importer
  template:
    metadata:
      annotations:
        vixens.io/fast-start: "true"
      labels:
        app.kubernetes.io/name: firefly-iii-importer
        vixens.io/sizing.importer: V-small
    spec:
      priorityClassName: vixens-low
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: importer
          image: fireflyiii/data-importer:version-2.1.1
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: FIREFLY_III_URL
              value: "http://firefly-iii.finance.svc.cluster.local"
            - name: VANITY_URL
              value: "https://importer.truxonline.com"
            - name: APP_URL
              value: "https://importer.truxonline.com"
            - name: TRUSTED_PROXIES
              value: "**"
            - name: HTTPS_ONLY
              value: "true"
            - name: TZ
              value: "Europe/Paris"
            - name: IGNORE_DUPLICATE_ERRORS
              value: "false"
            - name: CAN_POST_AUTOIMPORT
              value: "true"
            - name: CAN_POST_FILES
              value: "true"
          envFrom:
            - secretRef:
                name: firefly-iii-importer-secrets
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
