---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii-importer-secrets-sync
  namespace: finance
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: firefly-iii-importer-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/dev/apps/60-services/firefly-iii-importer
