---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydrus-client
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.hydrus-client: G-xl
        vixens.io/sizing.litestream: micro
