---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - infisical-secret.yaml
  - dashboards/traefik.yaml
  - dashboards/postgresql.yaml
  - dashboards/homeassistant.yaml
  - dashboards/trivy.yaml
  - dashboards/dataangel.yaml
  - dashboards/argocd.yaml
  - dashboards/velero.yaml
  - dashboards/cert-manager.yaml
  - dashboards/unifi-snmp.yaml
# Helm chart managed by ArgoCD
