---
apiVersion: v1
kind: Service
metadata:
  name: nexterm
  labels:
    app: nexterm
spec:
  selector:
    app: nexterm
  ports:
    - port: 80
      targetPort: 6989
      protocol: TCP
      name: http
