---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: indiba-portal
  namespace: indiba-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: >-
      traefik-redirect-https@kubernetescrd,
      auth-authentik-forward-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: agents.dev.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indiba-portal
                port:
                  number: 3000
  tls:
    - hosts:
        - agents.dev.truxonline.com
      secretName: indiba-portal-tls
