---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.mealie: small
        vixens.io/sizing.litestream: G-small
        vixens.io/sizing.config-syncer: G-small
    spec:
      containers:
        - name: mealie
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
