---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: netbird-dashboard
spec:
  endpointSelector:
    matchLabels:
      app: netbird-dashboard
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: netbird-management
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: netbird-management
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: networking
  egress:
    # netbird-management → authentik OIDC + geolocation DB download (world)
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
    - toEntities:
        - kube-apiserver
    # netbird-management → postgres (databases namespace)
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: databases
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: networking
