---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Before Kyverno policies that use ServiceMonitor apiCall
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/charchess/vixens.git
    targetRevision: prod-stable
    path: apps/00-infra/prometheus-operator-crds/base
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true # Required for large CRDs
