---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stalwart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  sources:
    - repoURL: oci://codeberg.org/wrenix/helm-charts/stalwart-mail
      chart: stalwart-mail
      targetRevision: 1.0.5
      helm:
        releaseName: stalwart
        valueFiles:
          - $values/apps/60-services/stalwart/values/prod.yaml
    - repoURL: https://github.com/charchess/vixens.git
      targetRevision: prod-stable
      ref: values
    - repoURL: https://github.com/charchess/vixens.git
      targetRevision: prod-stable
      path: apps/60-services/stalwart/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: stalwart
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
