---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: https://github.com/charchess/vixens.git
    targetRevision: prod-stable
    path: apps/70-tools/trilium/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      name: trilium-data-pvc
      jsonPointers:
        - /spec/storageClassName
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
