---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefly-iii
  labels:
    vixens.io/sizing: medium
spec:
  template:
    metadata:
      labels:
        app: firefly-iii
        vixens.io/sizing: medium
