---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: services
resources:
  - ../../base
  - ingress.yaml
components:
  - ../../../../_shared/components/gold-maturity

patches:
  - target:
      kind: InfisicalSecret
      name: openclaw-secrets
    patch: |-
      - op: replace
        path: /spec/authentication/universalAuth/secretsScope/envSlug
        value: prod
