---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
- ../../base
- ingress.yaml
- ingressroute-udp.yaml
components:
- ../../../../_shared/components/sync-wave/wave-6
- ../../../../_shared/components/goldilocks/enabled
- ../../../../_shared/components/nometrics
- ../../../../_shared/components/dataangel
- ../../../../_shared/components/poddisruptionbudget/1
- ../../../../_shared/components/scheduling/prefer-i915
patches:
- path: patch-openbao-env.yaml
- target:
    kind: PersistentVolumeClaim
    name: homeassistant-config
  patch: "- op: replace\n  path: /spec/storageClassName\n  value: synelia-iscsi-xfs-retain\n\
    - op: replace\n  path: /spec/resources/requests/storage\n  value: 250Gi"
- path: resources-patch.yaml
- path: dataangel.yaml
- path: anti-affinity-frigate.yaml
