---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-config-sync
  namespace: homeassistant
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/10-home/homeassistant
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homeassistant-secrets-sync
  namespace: homeassistant
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/10-home/homeassistant
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
