---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    vixens.io/sizing: G-xlarge
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing: G-xlarge
        vixens.io/sizing.homeassistant: G-xlarge
        vixens.io/sizing.litestream: G-small
        vixens.io/sizing.config-syncer: G-small
