---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  labels:
    vixens.io/sizing: V-large
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing: V-large
        vixens.io/sizing.homeassistant: V-large
        vixens.io/sizing.litestream: SB-medium
        vixens.io/sizing.config-syncer: B-small
