---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
resources:
  - ../../base
  - ingress.yaml
components:
  - ../../../../_shared/components/dev-hibernate
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bookstack
      spec:
        template:
          spec:
            containers:
              - name: bookstack
                env:
                  - name: APP_URL
                    value: "https://bookstack.dev.truxonline.com"
