---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mylar
  namespace: media
  labels:
    app: mylar
spec:
  selector:
    matchLabels:
      app: mylar
  namespaceSelector:
    matchNames:
      - media
  endpoints:
    - port: metrics
      targetPort: 9090
      path: /metrics
      interval: 60s
