---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: homeassistant
spec:
  endpointSelector:
    matchLabels:
      app: homeassistant
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
    - fromEntities:
        - host
        - remote-node
      toPorts:
        - ports:
            - port: "8123"
              protocol: TCP
