---
apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  environment: dev
kind: Kustomization
namespace: monitoring
patches:
- path: patch-alertmanager-command.yaml
  target:
    kind: StatefulSet
    name: prometheus-alertmanager
resources:
- ../../base
components:
- ../../../../_shared/components/dev-hibernate
