---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nocodb
  labels:
    vixens.io/sizing: medium
spec:
  template:
    metadata:
      labels:
        app: nocodb
        vixens.io/sizing: medium
