---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
resources:
  - ../../base
  - ingress.yaml
labels:
  - includeSelectors: false
    pairs:
      environment: prod
components:
  - ../../../../_shared/components/sync-wave/wave-15
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/nometrics
  - ../../../../_shared/components/dataangel

patches:
  - path: patch-infisical-env.yaml
  - path: dataangel.yaml
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path-delete
    target:
      kind: PersistentVolumeClaim
      name: amule-config-pvc
