---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docspell-joex-config
  labels:
    app: docspell
    component: joex
data:
  config: |
    docspell.joex {
      app-id = ${HOSTNAME}
      base-url = ${BASE_URL}
      bind {
        address = "0.0.0.0"
        port = 7878
      }
      jdbc {
        url = ${JDBC_URI}
        user = ${JDBC_USERNAME}
        password = ${JDBC_PASSWORD}
      }

      full-text-search {
        enabled = true
        backend = "postgresql"

        postgresql = {
          use-default-connection = true
        }
      }

      files {
        chunk-size = 524288
        valid-mime-types = []
        default-store = "minio"

        stores = {
          database { enabled = false, type = "default-database" }
          filesystem { enabled = false, type = "file-system", directory = "/tmp" }
          minio {
            enabled = true
            type = "s3"
            endpoint = "http://192.168.111.69:9000"
            access-key = ${MINIO_ACCESS_KEY}
            secret-key = ${MINIO_SECRET_KEY}
            bucket = "docspell"
            region = ""
          }
        }
      }
    }
