---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - infisical-secret.yaml

components:
  - ../../../../_shared/components/sync-wave/wave-11
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/nometrics
  - ../../../../_shared/components/dataangel
  - ../../../../_shared/components/poddisruptionbudget/1

patches:
  - target:
      kind: Deployment
      name: music-assistant
    path: resources-patch.yaml
  - path: dataangel.yaml
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path-retain
    target:
      kind: PersistentVolumeClaim
      name: music-assistant-config-pvc
