---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
spec:
  template:
    spec:
      containers:
        - name: music-assistant
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
