---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-assistant
  labels:
    vixens.io/sizing: medium
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing: medium
    spec:
      containers:
        - name: music-assistant
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 256Mi
