---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  template:
    metadata:
      labels:
        vixens.io/sizing.dataangel: B-nano
      annotations:
        data-guard.io/bucket: "vixens-dev-mealie"
        data-guard.io/sqlite-paths: "/app/data/mealie.db"
        data-guard.io/fs-paths: "/app/data"
        data-guard.io/s3-endpoint: "http://synelia.internal.truxonline.com:9000"
        data-guard.io/deployment-name: "mealie"
        data-guard.io/rclone-interval: "60s"
        data-guard.io/metrics-enabled: "true"
    spec:
      initContainers:
        - name: restore-config
          $patch: delete
        - name: restore-db
          $patch: delete
        - name: dataangel
          imagePullPolicy: Always
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 256Mi
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: LITESTREAM_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: LITESTREAM_SECRET_ACCESS_KEY
          volumeMounts:
            - name: data
              mountPath: /app/data
      containers:
        - name: litestream
          $patch: delete
        - name: config-syncer
          $patch: delete
