---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
- ../../base
labels:
- pairs:
    environment: prod
  includeSelectors: false
patches:
- path: patch-openbao-env.yaml
- patch: "- op: add\n  path: /spec/template/metadata/annotations/vixens.io~1no-long-connections\n\
    \  value: \"true\""
  target:
    kind: Deployment
    name: external-dns-gandi
