---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: networking
resources:
  - ../../base
components:
  - ../../../../_shared/components/infisical/env-prod
labels:
  - pairs:
      environment: prod
    includeSelectors: false

patches:
  # Graceful shutdown bypass — DNS sync controller, no user connections
  - patch: |-
      - op: add
        path: /spec/template/metadata/annotations/vixens.io~1no-long-connections
        value: "true"
    target:
      kind: Deployment
      name: external-dns-gandi
