---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: webhook
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cainjector
