---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.dataangel: V-small
      annotations:
        dataangel.io/bucket: "vixens-prod-netbox"
        dataangel.io/sqlite-paths: ""
        dataangel.io/fs-paths: "/opt/netbox/media"
        dataangel.io/s3-endpoint: "http://192.168.111.69:9000"
        dataangel.io/deployment-name: "netbox"
        dataangel.io/rclone-interval: "60s"
        dataangel.io/metrics-enabled: "true"
        dataangel.io/lock-enabled: "false"
    spec:
      initContainers:
        - name: dataangel
          securityContext:
            runAsUser: 999
            runAsGroup: 1000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: RCLONE_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: netbox-secrets
                  key: RCLONE_SECRET_ACCESS_KEY
          volumeMounts:
            - mountPath: /data
              $patch: delete
            - name: netbox-media
              mountPath: /opt/netbox/media
