---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-db-secrets-sync
  namespace: tools
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/70-tools/netbox
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbox-secrets-sync
  namespace: tools
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/70-tools/netbox
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
