---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: auth
  labels:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd, auth-authentik-cors@kubernetescrd
    vixens.io/nossoneeded: "true"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Security
    gethomepage.dev/name: Authentik
    gethomepage.dev/icon: authentik.svg
    gethomepage.dev/description: Identity provider & SSO
spec:
  ingressClassName: traefik
  rules:
    - host: authentik.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik
                port:
                  number: 9000
    - host: authentik.dev.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik
                port:
                  number: 9000
  tls:
    - hosts:
        - authentik.truxonline.com
        - authentik.dev.truxonline.com
      secretName: authentik-tls
