---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets-sync
  namespace: auth
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/03-security/authentik
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-redis-secret-sync
  namespace: auth
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/04-databases/redis-shared
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
