---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentik-worker
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.authentik-worker: V-large
      annotations:
        # authentik-worker V-large = 2560Mi
        vixens.io/vpa.max-memory: "2560Mi"
    spec:
      priorityClassName: vixens-critical
