---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- patch: "- op: replace\n  path: /spec/authentication/universalAuth/secretsScope/envSlug\n\
    \  value: dev"
  target:
    kind: InfisicalSecret
    name: frigate-secrets-sync
resources:
- ../../base
- ingress.yaml
components:
- ../../../../_shared/components/dev-hibernate
