---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-auth-sync
  namespace: mail
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mail-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
    - extract:
        key: vixens/prod/apps/60-services/mail/auth
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-dkim-sync
  namespace: mail
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mail-dkim
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
    - extract:
        key: vixens/prod/apps/60-services/mail/dkim
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-roundcube-sync
  namespace: mail
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mail-roundcube
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
    - extract:
        key: vixens/prod/apps/60-services/mail/roundcube
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-gmail-import-sync
  namespace: mail
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: mail-gmail-import
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
    - extract:
        key: vixens/prod/apps/60-services/mail/gmail-import
