---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - activation-gate.yaml
  - external-secrets.yaml
  - external-secrets-runtime.yaml
  - services.yaml
  - mailserver-statefulset.yaml
  - roundcube-deployment.yaml
  - external-secret-migration.yaml
  - migration-egress-policy.yaml
  - migration-job.yaml
  - mail-tls-certificate.yaml
