---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patch-infisical-env.yaml
  target:
    kind: InfisicalSecret
    name: pyload-secrets
resources:
- ../../base
- ingress.yaml
components:
- ../../../../_shared/components/dev-hibernate
