---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-9
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/nometrics
  - ../../../../_shared/components/poddisruptionbudget/1
patches:
  - path: dataangel.yaml
