---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booklore
  labels:
    vixens.io/sizing.booklore: medium
    vixens.io/sizing.config-syncer: small
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.booklore: medium
        vixens.io/sizing.config-syncer: small
