---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../../../_shared/components/base
  - ../../../../_shared/components/probes/basic

patches:
  # Dev: replicas=0 (disabled by default)
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: any
      spec:
        replicas: 0
    target:
      kind: Deployment

  # Dev: envSlug override
  - patch: |
      apiVersion: secrets.infisical.com/v1alpha1
      kind: InfisicalSecret
      metadata:
        name: any
      spec:
        authentication:
          universalAuth:
            secretsScope:
              envSlug: dev
    target:
      kind: InfisicalSecret
