---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: g4f-data
  labels:
    app.kubernetes.io/name: g4f
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
