---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/fabric.truxonline.io_tenantbundles.yaml
  - bases/fabric.truxonline.io_agentidentities.yaml
  - bases/fabric.truxonline.io_integrationconnections.yaml
  - bases/fabric.truxonline.io_integrationbindings.yaml
  - bases/fabric.truxonline.io_agentruntimeprofiles.yaml
  - bases/fabric.truxonline.io_postgresqlprofiles.yaml
  - bases/fabric.truxonline.io_hindsightprofiles.yaml
  - bases/fabric.truxonline.io_aigatewayprofiles.yaml
  - bases/fabric.truxonline.io_aicredentialbrokerprofiles.yaml
  - bases/fabric.truxonline.io_sharedworkspaceprofiles.yaml
