variable "git_branch" {}
variable "environment" {}
variable "vlan_services_subnet" {}
variable "argocd_service_type" {}
variable "argocd_loadbalancer_ip" {}
variable "argocd_disable_auth" {}
variable "argocd_hostname" {}
variable "cluster_name" {}
variable "cluster_endpoint" {}
variable "control_plane_nodes" {}
variable "worker_nodes" {}
variable "l2_pool_name" {}
variable "l2_pool_ips" {}
variable "l2_policy_name" {}
variable "l2_policy_interfaces" {}
variable "l2_policy_node_selector_labels" {}
variable "cluster_vip" {}
variable "argocd_insecure" {}
variable "argocd_anonymous_enabled" {}
variable "talos_version" {}
variable "kubernetes_version" {}
variable "talos_image" {}
variable "kubeconfig_path" {}
variable "talosconfig_path" {}
variable "cilium_ip_pool_yaml_path" {}
variable "cilium_l2_policy_yaml_path" {}
