//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentity) DeepCopyInto(out *AgentIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentity.
func (in *AgentIdentity) DeepCopy() *AgentIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentityList) DeepCopyInto(out *AgentIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentityList.
func (in *AgentIdentityList) DeepCopy() *AgentIdentityList {
	if in == nil {
		return nil
	}
	out := new(AgentIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AgentIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentitySpec) DeepCopyInto(out *AgentIdentitySpec) {
	*out = *in
	out.TenantRef = in.TenantRef
	out.Runtime = in.Runtime
	out.Memory = in.Memory
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentitySpec.
func (in *AgentIdentitySpec) DeepCopy() *AgentIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(AgentIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentIdentityStatus) DeepCopyInto(out *AgentIdentityStatus) {
	*out = *in
	out.Runtime = in.Runtime
	out.Memory = in.Memory
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AgentIdentityStatus.
func (in *AgentIdentityStatus) DeepCopy() *AgentIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(AgentIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AgentMemoryBinding) DeepCopyInto(out *AgentMemoryBinding) { *out = *in }
func (in *AgentMemoryBinding) DeepCopy() *AgentMemoryBinding { if in == nil { return nil }; out := new(AgentMemoryBinding); in.DeepCopyInto(out); return out }
func (in *AgentRuntimeBinding) DeepCopyInto(out *AgentRuntimeBinding) { *out = *in }
func (in *AgentRuntimeBinding) DeepCopy() *AgentRuntimeBinding { if in == nil { return nil }; out := new(AgentRuntimeBinding); in.DeepCopyInto(out); return out }

func (in *AgentRuntimeProfile) DeepCopyInto(out *AgentRuntimeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}
func (in *AgentRuntimeProfile) DeepCopy() *AgentRuntimeProfile { if in == nil { return nil }; out := new(AgentRuntimeProfile); in.DeepCopyInto(out); return out }
func (in *AgentRuntimeProfile) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *AgentRuntimeProfileList) DeepCopyInto(out *AgentRuntimeProfileList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]AgentRuntimeProfile, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *AgentRuntimeProfileList) DeepCopy() *AgentRuntimeProfileList { if in == nil { return nil }; out := new(AgentRuntimeProfileList); in.DeepCopyInto(out); return out }
func (in *AgentRuntimeProfileList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *AgentRuntimeProfileSpec) DeepCopyInto(out *AgentRuntimeProfileSpec) { *out = *in; in.Storage.DeepCopyInto(&out.Storage); in.Resources.DeepCopyInto(&out.Resources); out.Compatibility = in.Compatibility }
func (in *AgentRuntimeProfileSpec) DeepCopy() *AgentRuntimeProfileSpec { if in == nil { return nil }; out := new(AgentRuntimeProfileSpec); in.DeepCopyInto(out); return out }
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) { *out = *in }
func (in *ComponentStatus) DeepCopy() *ComponentStatus { if in == nil { return nil }; out := new(ComponentStatus); in.DeepCopyInto(out); return out }
func (in *HindsightMemorySpec) DeepCopyInto(out *HindsightMemorySpec) { *out = *in }
func (in *HindsightMemorySpec) DeepCopy() *HindsightMemorySpec { if in == nil { return nil }; out := new(HindsightMemorySpec); in.DeepCopyInto(out); return out }
func (in *MemoryBindingStatus) DeepCopyInto(out *MemoryBindingStatus) { *out = *in }
func (in *MemoryBindingStatus) DeepCopy() *MemoryBindingStatus { if in == nil { return nil }; out := new(MemoryBindingStatus); in.DeepCopyInto(out); return out }
func (in *ObjectReference) DeepCopyInto(out *ObjectReference) { *out = *in }
func (in *ObjectReference) DeepCopy() *ObjectReference { if in == nil { return nil }; out := new(ObjectReference); in.DeepCopyInto(out); return out }
func (in *PostgreSQLSpec) DeepCopyInto(out *PostgreSQLSpec) { *out = *in }
func (in *PostgreSQLSpec) DeepCopy() *PostgreSQLSpec { if in == nil { return nil }; out := new(PostgreSQLSpec); in.DeepCopyInto(out); return out }
func (in *RuntimeCompatibilitySpec) DeepCopyInto(out *RuntimeCompatibilitySpec) { *out = *in }
func (in *RuntimeCompatibilitySpec) DeepCopy() *RuntimeCompatibilitySpec { if in == nil { return nil }; out := new(RuntimeCompatibilitySpec); in.DeepCopyInto(out); return out }
func (in *RuntimeStatus) DeepCopyInto(out *RuntimeStatus) { *out = *in }
func (in *RuntimeStatus) DeepCopy() *RuntimeStatus { if in == nil { return nil }; out := new(RuntimeStatus); in.DeepCopyInto(out); return out }
func (in *RuntimeStorageSpec) DeepCopyInto(out *RuntimeStorageSpec) { *out = *in; out.Size = in.Size.DeepCopy() }
func (in *RuntimeStorageSpec) DeepCopy() *RuntimeStorageSpec { if in == nil { return nil }; out := new(RuntimeStorageSpec); in.DeepCopyInto(out); return out }

func (in *TenantBundle) DeepCopyInto(out *TenantBundle) { *out = *in; out.TypeMeta = in.TypeMeta; in.ObjectMeta.DeepCopyInto(&out.ObjectMeta); in.Spec.DeepCopyInto(&out.Spec); in.Status.DeepCopyInto(&out.Status) }
func (in *TenantBundle) DeepCopy() *TenantBundle { if in == nil { return nil }; out := new(TenantBundle); in.DeepCopyInto(out); return out }
func (in *TenantBundle) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *TenantBundleList) DeepCopyInto(out *TenantBundleList) { *out = *in; out.TypeMeta = in.TypeMeta; in.ListMeta.DeepCopyInto(&out.ListMeta); if in.Items != nil { in, out := &in.Items, &out.Items; *out = make([]TenantBundle, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *TenantBundleList) DeepCopy() *TenantBundleList { if in == nil { return nil }; out := new(TenantBundleList); in.DeepCopyInto(out); return out }
func (in *TenantBundleList) DeepCopyObject() runtime.Object { if c := in.DeepCopy(); c != nil { return c }; return nil }
func (in *TenantBundleSpec) DeepCopyInto(out *TenantBundleSpec) { *out = *in; out.Isolation = in.Isolation; in.Persistence.DeepCopyInto(&out.Persistence); in.Memory.DeepCopyInto(&out.Memory); if in.Modules != nil { in, out := &in.Modules, &out.Modules; *out = make([]TenantModuleSpec, len(*in)); copy(*out, *in) } }
func (in *TenantBundleSpec) DeepCopy() *TenantBundleSpec { if in == nil { return nil }; out := new(TenantBundleSpec); in.DeepCopyInto(out); return out }
func (in *TenantBundleStatus) DeepCopyInto(out *TenantBundleStatus) { *out = *in; in.Persistence.DeepCopyInto(&out.Persistence); in.Memory.DeepCopyInto(&out.Memory); if in.Modules != nil { in, out := &in.Modules, &out.Modules; *out = make([]TenantModuleStatus, len(*in)); copy(*out, *in) }; if in.Conditions != nil { in, out := &in.Conditions, &out.Conditions; *out = make([]v1.Condition, len(*in)); for i := range *in { (*in)[i].DeepCopyInto(&(*out)[i]) } } }
func (in *TenantBundleStatus) DeepCopy() *TenantBundleStatus { if in == nil { return nil }; out := new(TenantBundleStatus); in.DeepCopyInto(out); return out }
func (in *TenantIsolationSpec) DeepCopyInto(out *TenantIsolationSpec) { *out = *in }
func (in *TenantIsolationSpec) DeepCopy() *TenantIsolationSpec { if in == nil { return nil }; out := new(TenantIsolationSpec); in.DeepCopyInto(out); return out }
func (in *TenantMemorySpec) DeepCopyInto(out *TenantMemorySpec) { *out = *in; if in.Hindsight != nil { in, out := &in.Hindsight, &out.Hindsight; *out = new(HindsightMemorySpec); **out = **in } }
func (in *TenantMemorySpec) DeepCopy() *TenantMemorySpec { if in == nil { return nil }; out := new(TenantMemorySpec); in.DeepCopyInto(out); return out }
func (in *TenantMemoryStatus) DeepCopyInto(out *TenantMemoryStatus) { *out = *in; if in.Hindsight != nil { in, out := &in.Hindsight, &out.Hindsight; *out = new(ComponentStatus); **out = **in } }
func (in *TenantMemoryStatus) DeepCopy() *TenantMemoryStatus { if in == nil { return nil }; out := new(TenantMemoryStatus); in.DeepCopyInto(out); return out }
func (in *TenantModuleSpec) DeepCopyInto(out *TenantModuleSpec) { *out = *in }
func (in *TenantModuleSpec) DeepCopy() *TenantModuleSpec { if in == nil { return nil }; out := new(TenantModuleSpec); in.DeepCopyInto(out); return out }
func (in *TenantModuleStatus) DeepCopyInto(out *TenantModuleStatus) { *out = *in; out.ComponentStatus = in.ComponentStatus }
func (in *TenantModuleStatus) DeepCopy() *TenantModuleStatus { if in == nil { return nil }; out := new(TenantModuleStatus); in.DeepCopyInto(out); return out }
func (in *TenantPersistenceSpec) DeepCopyInto(out *TenantPersistenceSpec) { *out = *in; if in.PostgreSQL != nil { in, out := &in.PostgreSQL, &out.PostgreSQL; *out = new(PostgreSQLSpec); **out = **in } }
func (in *TenantPersistenceSpec) DeepCopy() *TenantPersistenceSpec { if in == nil { return nil }; out := new(TenantPersistenceSpec); in.DeepCopyInto(out); return out }
func (in *TenantPersistenceStatus) DeepCopyInto(out *TenantPersistenceStatus) { *out = *in; if in.PostgreSQL != nil { in, out := &in.PostgreSQL, &out.PostgreSQL; *out = new(ComponentStatus); **out = **in } }
func (in *TenantPersistenceStatus) DeepCopy() *TenantPersistenceStatus { if in == nil { return nil }; out := new(TenantPersistenceStatus); in.DeepCopyInto(out); return out }
