//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *AgentIdentity) DeepCopyInto(out *AgentIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	if in.Status.Conditions != nil {
		out.Status.Conditions = conditionSliceCopy(in.Status.Conditions)
	}
}

func (in *AgentIdentity) DeepCopy() *AgentIdentity {
	if in == nil {
		return nil
	}
	out := new(AgentIdentity)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentIdentityList) DeepCopyInto(out *AgentIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentIdentity, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentIdentityList) DeepCopy() *AgentIdentityList {
	if in == nil {
		return nil
	}
	out := new(AgentIdentityList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentRuntimeProfile) DeepCopyInto(out *AgentRuntimeProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Spec.Storage.Size = in.Spec.Storage.Size.DeepCopy()
	in.Spec.Resources.DeepCopyInto(&out.Spec.Resources)
}

func (in *AgentRuntimeProfile) DeepCopy() *AgentRuntimeProfile {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeProfile)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentRuntimeProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AgentRuntimeProfileList) DeepCopyInto(out *AgentRuntimeProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]AgentRuntimeProfile, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *AgentRuntimeProfileList) DeepCopy() *AgentRuntimeProfileList {
	if in == nil {
		return nil
	}
	out := new(AgentRuntimeProfileList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentRuntimeProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TenantBundle) DeepCopyInto(out *TenantBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	if in.Spec.Persistence.PostgreSQL != nil {
		out.Spec.Persistence.PostgreSQL = new(PostgreSQLSpec)
		*out.Spec.Persistence.PostgreSQL = *in.Spec.Persistence.PostgreSQL
	}
	if in.Spec.Memory.Hindsight != nil {
		out.Spec.Memory.Hindsight = new(HindsightMemorySpec)
		*out.Spec.Memory.Hindsight = *in.Spec.Memory.Hindsight
	}
	if in.Spec.Modules != nil {
		out.Spec.Modules = make([]TenantModuleSpec, len(in.Spec.Modules))
		copy(out.Spec.Modules, in.Spec.Modules)
	}
	out.Status = in.Status
	if in.Status.Persistence.PostgreSQL != nil {
		out.Status.Persistence.PostgreSQL = new(ComponentStatus)
		*out.Status.Persistence.PostgreSQL = *in.Status.Persistence.PostgreSQL
	}
	if in.Status.Memory.Hindsight != nil {
		out.Status.Memory.Hindsight = new(ComponentStatus)
		*out.Status.Memory.Hindsight = *in.Status.Memory.Hindsight
	}
	if in.Status.Modules != nil {
		out.Status.Modules = make([]TenantModuleStatus, len(in.Status.Modules))
		copy(out.Status.Modules, in.Status.Modules)
	}
	if in.Status.Conditions != nil {
		out.Status.Conditions = conditionSliceCopy(in.Status.Conditions)
	}
}

func (in *TenantBundle) DeepCopy() *TenantBundle {
	if in == nil {
		return nil
	}
	out := new(TenantBundle)
	in.DeepCopyInto(out)
	return out
}

func (in *TenantBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TenantBundleList) DeepCopyInto(out *TenantBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]TenantBundle, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *TenantBundleList) DeepCopy() *TenantBundleList {
	if in == nil {
		return nil
	}
	out := new(TenantBundleList)
	in.DeepCopyInto(out)
	return out
}

func (in *TenantBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
