---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stalwart-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    vixens.io/nossoneeded: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: stalwart.dev.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stalwart
                port:
                  number: 8080
  tls:
    - hosts:
        - stalwart.dev.truxonline.com
      secretName: stalwart-tls
