---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: APP_NAME-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synelia-iscsi-retain
  resources:
    requests:
      storage: 5Gi
