---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-9
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/nometrics

patches:
