---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii-importer-secrets-sync
  namespace: finance
spec:
  dataFrom:
  - extract:
      key: vixens/prod/apps/60-services/firefly-iii-importer
  target:
    template:
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
