---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - servicemonitor.yaml

components:
  - ../../../../_shared/components/sync-wave/wave-3
  - ../../../../_shared/components/goldilocks/enabled

patches:
  - path: resources-patch.yaml
  - path: node-collector-patch.yaml
  - path: fast-start-patch.yaml
  - patch: |-
      - op: add
        path: /spec/template/metadata/annotations/vixens.io~1no-long-connections
        value: "true"
    target:
      kind: Deployment
      name: trivy-trivy-operator
