---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-trivy-operator
  namespace: security
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.trivy-operator: G-large
    spec:
      priorityClassName: vixens-medium
      containers:
        - name: trivy-operator
          livenessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 10
