---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docspell-db-credentials-sync
  labels:
    app: docspell
  namespace: services
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: docspell-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/prod/apps/60-services/docspell
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: docspell-secrets-sync
  labels:
    app: docspell
  namespace: services
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: docspell-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/prod/apps/60-services/docspell
