---
apiVersion: v1
kind: Service
metadata:
  name: sogo
  namespace: sogo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: sogo
    app.kubernetes.io/name: sogo
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
