---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    environment: dev
namespace: services
resources:
- ../../base
components:
- ../../../../_shared/components/dev-hibernate
