---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-metrics
  namespace: monitoring
  labels:
    app: hubble-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hubble
      app.kubernetes.io/part-of: cilium
  namespaceSelector:
    matchNames:
      - kube-system
  endpoints:
    - port: hubble-metrics
      path: /metrics
      interval: 30s
