---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - servicemonitor.yaml

components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-11
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/revision-history-limit
  - ../../../../_shared/components/dataangel

patches:
  - path: dataangel.yaml
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: local-path-retain
    target:
      kind: PersistentVolumeClaim
      name: n8n-config-pvc
