---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - servicemonitor.yaml

components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-11
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/revision-history-limit
  - ../../../../_shared/components/dataangel
  - ../../../../_shared/components/poddisruptionbudget/1
  - ../../../../_shared/components/scheduling/avoid-i915

patches:
  - path: dataangel.yaml
