---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: netvisor-ingress
  labels:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-https@kubernetescrd
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: NetVisor
    gethomepage.dev/icon: netvisor.png
    gethomepage.dev/group: Network
    vixens.io/nossoneeded: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: netvisor.truxonline.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keda-interceptor-proxy
                port:
                  number: 8080
  tls:
    - hosts:
        - netvisor.truxonline.com
      secretName: netvisor-tls
