---
apiVersion: v1
kind: Service
metadata:
  name: keda-interceptor-proxy
  namespace: networking
spec:
  type: ExternalName
  externalName: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
  ports:
    - port: 60072
      protocol: TCP
