---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  template:
    metadata:
      labels:
        vixens.io/sizing.sonarr: small
        vixens.io/sizing.litestream: micro
        vixens.io/sizing.config-syncer: micro
