#!/usr/bin/env python3
import argparse
import sys
import os
import json
from datetime import datetime

# Add lib to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib'))

from report_utils import parse_markdown_table, save_markdown_table

def main():
    parser = argparse.ArgumentParser(description="Generate STATUS.md from cluster state and conformity reports")
    parser.add_argument("--dev-state", help="Dev state JSON file (generated by generate-actual-state.py)")
    parser.add_argument("--prod-state", help="Prod state JSON file (generated by generate-actual-state.py)")
    parser.add_argument("--dev-conformity", help="Dev conformity report file")
    parser.add_argument("--prod-conformity", help="Prod conformity report file")
    parser.add_argument("--output", default="docs/reports/STATUS.md", help="Output status dashboard file")
    args = parser.parse_args()

    # Load Conformity Data (Technical Score)
    dev_conf_rows = parse_markdown_table(args.dev_conformity) if args.dev_conformity else []
    prod_conf_rows = parse_markdown_table(args.prod_conformity) if args.prod_conformity else []

    dev_conf_map = {row['App'].replace('**', ''): row for row in dev_conf_rows if 'App' in row}
    prod_conf_map = {row['App'].replace('**', ''): row for row in prod_conf_rows if 'App' in row}

    # Load Functional State Data (Health)
    dev_state = {}
    if args.dev_state and os.path.exists(args.dev_state):
        with open(args.dev_state, 'r') as f:
            dev_state = json.load(f)
            
    prod_state = {}
    if args.prod_state and os.path.exists(args.prod_state):
        with open(args.prod_state, 'r') as f:
            prod_state = json.load(f)

    # All unique apps
    all_apps = sorted(set(list(prod_conf_map.keys()) + list(dev_conf_map.keys()) + list(dev_state.keys()) + list(prod_state.keys())))

    # Summary counts
    stats = {"OK": 0, "NOK": 0, "HIBERNATED": 0, "ABSENT": 0}
    
    matrix_rows = []
    headers = ["Application", "Dev", "Prod", "Conformity", "Last Change", "Note"]

    # Use ASCII/Universal symbols instead of Emojis for better compatibility
    def get_functional_icon(state_data):
        if not state_data:
            return "⚪ --"
        
        health = state_data.get('health', 'Unknown')
        sync = state_data.get('sync', 'Unknown')
        
        if health == 'Healthy' and sync == 'Synced':
            return "✅ OK"
        elif health == 'Suspended' or health == 'Missing': 
             return "💤 HIB"
        else:
            return "❌ NOK"

    def get_progress_bar(score_str):
        try:
            score = int(score_str.split('/')[0])
        except:
            score = 0
        
        blocks = int(score / 10)
        bar = "▓" * blocks + "░" * (10 - blocks)
        return f"[{bar}] {score} %"

    for app_name in all_apps:
        # Determine Functional State
        dev_info = dev_state.get(app_name)
        prod_info = prod_state.get(app_name)
        
        dev_icon = get_functional_icon(dev_info)
        prod_icon = get_functional_icon(prod_info)

        # Determine Conformity (Technical)
        conf_data = prod_conf_map.get(app_name) or dev_conf_map.get(app_name)
        
        score_str = "0/100"
        issues = ""
        if conf_data:
            score_str = conf_data.get('Score', '0/100')
            issues = conf_data.get('Issues', '')

        # ASCII Progress Bar
        conformity_display = get_progress_bar(score_str)

        # Update Prod Statistics
        if "OK" in prod_icon: stats["OK"] += 1
        elif "HIB" in prod_icon: stats["HIBERNATED"] += 1
        elif "NOK" in prod_icon: stats["NOK"] += 1
        else: stats["ABSENT"] += 1

        matrix_rows.append({
            "Application": f"**{app_name}**",
            "Dev": dev_icon,
            "Prod": prod_icon,
            "Conformity": conformity_display,
            "Last Change": datetime.now().strftime('%Y-%m-%d'),
            "Note": issues
        })

    # Generate Content
    content = "# Application Status Dashboard\n\n"
    content += f"**Last Updated:** {datetime.now().strftime('%Y-%m-%d')}\n"
    content += "**Cluster Environments:** dev, prod\n\n---\n\n"
    
    content += "## Overview (Prod Cluster)\n\n"
    overview_headers = ["Category", "Count", "Total"]
    total = sum(stats.values())
    overview_rows = [
        {"Category": "✅ OK (Functional)", "Count": str(stats["OK"]), "Total": str(total)},
        {"Category": "❌ NOK (Broken)", "Count": str(stats["NOK"]), "Total": str(total)},
        {"Category": "💤 Hibernated", "Count": str(stats["HIBERNATED"]), "Total": str(total)},
        {"Category": "⚪ Absent", "Count": str(stats["ABSENT"]), "Total": str(total)},
        {"Category": "Total", "Count": str(total), "Total": str(total)}
    ]
    content += save_markdown_table(overview_headers, overview_rows)
    content += "\n\n---\n\n"
    
    content += "## Application Status Matrix\n\n"
    content += save_markdown_table(headers, matrix_rows)
    content += "\n"

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"Status dashboard generated: {args.output}")

if __name__ == "__main__":
    main()
