---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookshelf-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-delete
  resources:
    requests:
      storage: 4Gi
