---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mealie
spec:
  endpointSelector:
    matchLabels:
      app: mealie
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
      toPorts:
        - ports:
            - port: "9000"
              protocol: TCP
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: monitoring
  egress:
    - {}
