---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeTemplates: true
    pairs:
      cache-bust: '2'
      vixens.lab/environment: dev
namespace: synology-csi
components:
  - ../../../../_shared/components/dev-hibernate
patches:
  - patch: |-
      - op: replace
        path: /parameters/igroup
        value: "vixens-dev-iscsi-group"
      - op: add
        path: /parameters/targetIps
        value: "192.168.111.70,192.168.111.71"
    target:
      kind: StorageClass
      name: synelia-iscsi-retain
  - patch: |-
      - op: add
        path: /parameters/igroup
        value: "vixens-dev-iscsi-group"
      - op: add
        path: /parameters/targetIps
        value: "192.168.111.70,192.168.111.71"
    target:
      kind: StorageClass
      name: synelia-iscsi-delete
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: synology-csi-node
      spec:
        template:
          spec:
            containers:
              - name: synology-csi-plugin
                image: ghcr.io/zebernst/synology-csi:edge
    target:
      kind: DaemonSet
      name: synology-csi-node
resources:
  - ../../base
