---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nightscout
spec:
  podSelector:
    matchLabels:
      app: nightscout
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 1337
  egress:
    - {}
