---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- middleware.yaml
- ingress.yaml
components:
- ../../../../_shared/components/dev-hibernate
- ../../../../_shared/components/probes/basic
