---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - argocd-crds.yaml
  - argocd-install.yaml
  - servicemonitor.yaml
components:
  - ../../../_shared/components/revision-history-limit
