---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - keda-scaledobjects.yaml
components:
  - ../../../../_shared/components/infisical/env-prod
  - ../../../../_shared/components/sync-wave/wave-11
  - ../../../../_shared/components/goldilocks/enabled
  - ../../../../_shared/components/nometrics
labels:
  - pairs:
      environment: prod
    includeSelectors: false
