---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: infisical-patch.yaml
  target:
    kind: InfisicalSecret
    name: external-dns-unifi-sync
resources:
- ../../base
components:
- ../../../../_shared/components/dev-hibernate
