---
apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-repo-maintenance-config
  namespace: velero
data:
  config.json: |
    {
      "global": {
        "keepLatestMaintenanceJobs": 3,
        "podResources": {
          "cpuRequest": "100m",
          "memoryRequest": "256Mi",
          "cpuLimit": "500m",
          "memoryLimit": "1Gi"
        }
      }
    }
