---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    environment: dev
resources:
- ../../base
- ingress.yaml
components:
- ../../../../_shared/components/dev-hibernate
patches:
- path: patches/dataangel-test.yaml
  target:
    kind: Deployment
    name: mealie
- patch: |-
    - op: replace
      path: /spec/template/spec/volumes/0
      value:
        name: data
        emptyDir: {}
  target:
    kind: Deployment
    name: mealie
