---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-postgresql-credentials
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: linkwarden-postgresql-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          vixens.io/secret-source: openbao
  dataFrom:
  - extract:
      key: vixens/dev/apps/70-tools/linkwarden
