---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mariadb-shared
spec:
  endpointSelector:
    matchLabels:
      app: mariadb-shared
  ingress:
    - fromEndpoints:
        - {}
      toPorts:
        - ports:
            - port: "3306"
              protocol: TCP
  egress:
    - {}
