---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-csi-iscsi-driver-config
  namespace: truenas-csi
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: truenas-csi-iscsi-driver-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: vixens/dev/apps/01-storage/truenas-csi/iscsi
        property: driver-config-file.yaml
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: truenas-csi-nfs-driver-config
  namespace: truenas-csi
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: openbao-umi
    kind: ClusterSecretStore
  target:
    name: truenas-csi-nfs-driver-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
  data:
    - secretKey: driver-config-file.yaml
      remoteRef:
        key: vixens/dev/apps/01-storage/truenas-csi/nfs
        property: driver-config-file.yaml
