---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hermes-default.yaml
  - hermes-dev.yaml
  - hermes-upgrade-canary.yaml
  - postgresql-shared.yaml
  - postgresql-litellm.yaml
  - hindsight-standard.yaml
  - hindsight-gateway.yaml
  - cliproxyapi-standard.yaml
  - litellm-standard.yaml
  - workspace-shared.yaml
  - hermes-2026-09-24-fca358f12efd-33060387a98b.yaml
  - hermes-2026-09-24-fca358f12efd-65c6d3204b9f.yaml
