---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: velero
spec:
  template:
    spec:
      containers:
        - name: node-agent
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /metrics
              port: 8085
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 30  # 5 min max startup time
