---
apiVersion: fabric.truxonline.io/v1alpha1
kind: TenantBundle
metadata:
  name: hairem
  labels:
    app.kubernetes.io/part-of: txo-fabric
spec:
  tenantId: TEN00001
  displayName: hAIrem
  isolation:
    profile: Shared
  persistence:
    postgresql:
      mode: Shared
      profileRef: postgresql-shared
  memory:
    hindsight:
      profileRef: hindsight-gateway
      humanAccess: true
  workspace:
    profileRef: shared-nfs
    retentionPolicy: Retain
    groups:
      - name: admin
        collaborative: true
        skillsCollaborative: true
    users:
      - name: charchess
        collaborative: true
        skillsCollaborative: true
  humanAccess:
    web:
      iamGroups:
        - client0
      domainSuffix: truxonline.com
      ingressClassName: traefik
      tlsClusterIssuer: letsencrypt-prod
      publicDNS: true
      dnsTarget: truxonline.com
      oidc:
        issuer: https://authentik.truxonline.com/application/o/txo-fabric-hairem/
        clientId: txo-fabric-hairem
        scopes: openid profile email
