---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mongodb-shared
spec:
  endpointSelector:
    matchLabels:
      app: mongodb-shared
  ingress:
    # fromEndpoints: [{}] cassé dans Cilium 1.18.3 → fromEntities: cluster
    - fromEntities:
        - cluster
      toPorts:
        - ports:
            - port: "27017"
              protocol: TCP
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "9000"
              protocol: TCP
