---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: mongodb-shared-credentials
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  hostAPI: http://192.168.111.69:8085
  authentication:
    universalAuth:
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: argocd
      secretsScope:
        projectSlug: vixens
        envSlug: dev
        secretsPath: /apps/04-databases/mongodb-shared
  managedSecretReference:
    secretName: mongodb-shared-credentials
    creationPolicy: Owner
    secretNamespace: databases
