---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-shared
spec:
  podSelector:
    matchLabels:
      app: mongodb-shared
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: 27017
  egress:
    - {}
