---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  labels:
    vixens.io/sizing: small
spec:
  template:
    metadata:
      labels:
        app: argocd-server
        vixens.io/sizing: small
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  labels:
    vixens.io/sizing: small
spec:
  template:
    metadata:
      labels:
        app: argocd-repo-server
        vixens.io/sizing: small
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: argocd-repo-server
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    metadata:
      labels:
        app: argocd-application-controller
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: argocd-application-controller
          resources:
            requests:
              cpu: 500m
              memory: 400Mi
            limits:
              cpu: "1"
              memory: 2Gi
