---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yaml
  - httpscaledobject.yaml

components:
  - ../../../../_shared/components/sync-wave/wave-11
  - ../../../../_shared/components/goldilocks/enabled

patches:
