---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: headlamp
spec:
  endpointSelector:
    matchLabels:
      app: headlamp
  ingress:
    - fromEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: traefik
        - matchLabels:
            io.kubernetes.pod.namespace: keda
      toPorts:
        - ports:
            - port: "4466"
              protocol: TCP
  egress:
    - {}
