---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  labels:
    app: headlamp
    vixens.io/sizing-v2: "true"
    vixens.io/vpa-mode: Auto
    vixens.io/tier: "diamond"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
        vixens.io/sizing.headlamp: V-small
      annotations:
        reloader.stakater.com/auto: "true"
        vixens.io/fast-start: "true"
        vixens.io/nometrics: "true"
        vixens.io/no-long-connections: "true"
    spec:
      serviceAccountName: headlamp
      priorityClassName: vixens-medium
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.40.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4466
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: HEADLAMP_BASE_URL
              value: /
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
