---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfarr-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synelia-iscsi-delete
  resources:
    requests:
      storage: 5Gi
