---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shelfarr-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path-delete
  resources:
    requests:
      storage: 5Gi
