---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools
labels:
  - pairs:
      environment: prod
resources:
  - ../../base
  - pvc.yaml
  - report-exporter-configmap.yaml
  - victoriametrics-egress.yaml
patches:
  - path: patch-external-secret-env.yaml
  - path: resources-patch.yaml
  - path: report-export-patch.yaml
  - path: work-volume-patch.yaml
