---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: work
              $patch: replace
              persistentVolumeClaim:
                claimName: renovate-cache
